spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${env.PG_HOST}:${env.PG_PORT}/${env.PG_DB}"
    username: ${env.PG_USER}
    password: ${env.PG_PASSWORD}
    hikari:
      jdbc-url: ${spring.datasource.url}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: "classpath:yourpackage/db/db.changelog-main.yml"

server:
  port: ${env.API_PORT:8080}

api:
  web:
    base: ${env.WEB_BASE}
  jwt:
    secret: ${env.API_JWT_SECRET}
    issuer: ${env.API_JWT_ISSUER}
    expires: ${env.API_JWT_EXPIRE_MINUTE}
