# 개발환경

spring:
  liquibase:
    change-log: "classpath:db/dev.yml"
    clear-checksums: true

server:
  ssl:
    enabled: true
    key-store: "classpath:localhost.p12"
    key-store-type: PKCS12
    key-password: ""
    key-store-password: ""


.env:
  prefix: ""
  systemProperties: true
  directory: common
  filename: .env.dev
