# 어플리케이션 설정
projectname:
  auth:
    issuer: ${PPALLI_AUTH_ISSUER}
    secret: ${PPALLI_AUTH_SECRET}
    access-token-expires: ${PPALLI_AUTH_EXPIRES}
    refresh-token-expires: ${PPALLI_AUTH_REFRESH_EXPIRE}

# Spring boot 설정
spring:
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${PPALLI_DB_HOST}:${PPALLI_DB_PORT}/${PPALLI_DB_DATABASE}"
    username: ${PPALLI_DB_USERNAME}
    password: ${PPALLI_DB_PASSWORD}
  redis:
    host: ${PPALLI_REDIS_HOST}
    port: ${PPALLI_REDIS_PORT}
  liquibase:
    change-log: "classpath:db/main.yml" # 데이터베이스 마이그레이션 설정 파일 위치
  jpa:
    show-sql: false # 보안
    open-in-view: false # 성능
    hibernate:
      ddl-auto: validate # 어플리케이션 시작 시 DB 검증

# Tomcat 설정
server:
  error:
    whitelabel.enabled: false
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false

.env:
  prefix: ""
  systemProperties: true
